### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by harisreedhar** [harisreedhar/Swap-Mukham#30]
## High Priority task:
- [x] **face swap by condition**
    - [x] specific face by similarity
    - [x] position (top/bottom/left/right most face)
    - [x] size (biggest & smallest face)
    - [x] gender & age   
- [ ] **Add support face enhancers** 
    - [x] GFPGAN
    - [x]  RealESRGAN
    - [ ] Codeformer
    - [ ] DMDNET 
    - [ ] PSFRGAN
- [ ] **Optimization**
    - [ ] lower ram usage
    - [ ] optimize face analysis
    - [x] optimize swapping
    - [ ] optimize face parsing 
    - [ ] optimize face enhancement
    - [x] optimize post-processing
- [ ] **Color transfer & seamless blending**
    - [x] Laplacian blending
    - [ ] Multiband blending
- [ ] **Better face mask (remove seams)**
- [ ] **Improve video trim tools** 
- [ ] **Improve gui and preview**
- [ ] **Adjustable output settings**
- [ ] **Test preview**

## Low Priority task:
- [ ] **Include more swapping methods**
    - [ ] Sber-swap
    - [ ] Sim-swap
    - [ ] Info-swap
    - [ ] Megafs
- [ ] **One click installer**
- [ ] **Simple video editing tools**
- [ ] **Streaming through webcam**
- [ ] **Support for non-cuda users?**

**Comment by mukeshsnp12** [comment]
Please check https://github.com/zhaoyun0071/roop-windows-GUI for standalone portable app
It's faster than linux on windows.

**Comment by harisreedhar** [comment]
> Please check https://github.com/zhaoyun0071/roop-windows-GUI for standalone portable app It's faster than linux on windows.

No public source code in the given link.

**Comment by mukeshsnp12** [comment]
Yes, right
I downloaded and installed on my laptop windows 11
The folder has all the requirements in same folder (similar to virtual environment), All the required packages are in 1 folder. Then there is an exe file 41 MB, on running of exe file python environment open and process happen as in your GUI. 
1st it extract frames, then it swap all frames without using gfpgan, then after gfpgan start working and all images get enhanced. then it create video file. 
What Swap-mukham is doing is opposite to this. Swap mukham is storing swapping data 1st in memory and then enhancing data in memory and doing both swapping and enhancing as post processing. 
In the very 1st version of Swap-Mukham, Swap-Mukham was doing same as this GUI.

**Comment by mukeshsnp12** [comment]
@harisreedhar Can you add clip function?
Please check https://github.com/Hillobar/Rope
clip gives an option to choose positive and negative subjects. It keeps all subject/objects mention in negative box. It's great and very helpful.

**Comment by rauldlnx10** [comment]
ControlNet possible? i think its a good idea to use medapipe face or Canny for detection and details, I have found onnx models:
https://huggingface.co/ForserX

**Comment by harisreedhar** [comment]
> ControlNet possible? i think its a good idea to use medapipe face or Canny for detection and details, I have found onnx models:
> https://huggingface.co/ForserX

Mediapipe is very fast but accuracy is not good as retinaface. What is canny? Is it a face detector?

**Comment by mukeshsnp12** [comment]
Canny is marking and detection model for controlnet

**Comment by harisreedhar** [comment]
@mukeshsnp12 how is that useful for face swap?

**Comment by mukeshsnp12** [comment]
> @mukeshsnp12 how is that useful for face swap?

It can detect more points on whole body or face. Usually, it is used to generate new action of an image.

**Comment by mukeshsnp12** [comment]
@harisreedhar I am not sure, if it is useful for face swapping.

**Comment by mukeshsnp12** [comment]
@harisreedhar if we can find some other model like X-seg used by Deepfacelab for face detection, then it will be great. Insightface do not detect face as good as xseg does.

**Comment by harisreedhar** [comment]
@mukeshsnp12 Isn't x-seg a face segmentation model that require manual masking and training?

**Comment by mukeshsnp12** [comment]
> @mukeshsnp12 Isn't x-seg a face segmentation model that require manual masking and training?

Yes, that's problem

**Comment by harisreedhar** [comment]
@mukeshsnp12 

I implemented(not public yet) xseg model in swap-mukham. With this implementation users can use their own xseg model easily. Here is the test result with a free community model:
![occlusion_test](https://github.com/harisreedhar/Swap-Mukham/assets/46858047/b0161295-21e7-4c39-bc96-79349eec43ab)

**Comment by mukeshsnp12** [comment]
@harisreedhar  This look great, waiting eagerly to test

**Comment by mukeshsnp12** [comment]
@harisreedhar are you not updating?

**Comment by harisreedhar** [comment]
@mukeshsnp12 Sorry for the delay. Since there are no sponsors i only work on this project in my free time. there are lot of issues to resolve before releasing it. Here is a WIP preview:

https://github.com/harisreedhar/Swap-Mukham/assets/46858047/2235407b-c417-46f4-8ba6-9afb4e08eb45

**Comment by mukeshsnp12** [comment]
@harisreedhar seems great update

**Comment by RFedz007** [comment]
> @mukeshsnp12 Sorry for the delay. Since there are no sponsors i only work on this project in my free time. there are lot of issues to resolve before releasing it. Here is a WIP preview:
> 
>  prev2.mp4

Great Awesome :) The last frame where you clicked "position" & then the mask came intact with the face makes it look very Real :) Eagerly waiting for this to try... Is there still time for this update! to come out. Thank You

**Comment by CeeBeeEh** [comment]
Any eta on a release for these latest changes? I have a few additions I made that I would like to create a PR for, but a lot of it is based on the main branch. So I would need to pull the latest from the WIP branch to merge things on my end first.

**Comment by harisreedhar** [comment]
> Any eta on a release for these latest changes? I have a few additions I made that I would like to create a PR for, but a lot of it is based on the main branch. So I would need to pull the latest from the WIP branch to merge things on my end first.

I refactored the code. now It is very different from main & WIP branch. I have added lot of features without proper testing so releasing it now might be bad idea. may be next week idk.

**Comment by morisuba** [comment]
thank you very much . waiting 🤞

**Comment by morisuba** [comment]
> > Any eta on a release for these latest changes? I have a few additions I made that I would like to create a PR for, but a lot of it is based on the main branch. So I would need to pull the latest from the WIP branch to merge things on my end first.
> 
> I refactored the code. now It is very different from main & WIP branch. I have added lot of features without proper testing so releasing it now might be bad idea. may be next week idk.

did you test the new features?
